name: Update manufacturer file

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update_manufacturer_file:
    name: Update manufacturer file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Setup Python
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6
        with:
          python-version: "3.14.2"

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r tools/requirements.txt

      - name: Make manufacturer file
        run: python tools/make_manuf.py

      - name: Check if there are any changes
        id: verify_diff
        run: |
          git diff --quiet . || echo "changed=true" >> $GITHUB_OUTPUT

      - name: Update manufacturer file
        if: steps.verify_diff.outputs.changed == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add manuf.txt
          git commit -am "manuf: Update of `date +'%Y-%m-%d %H:%M:%S'`"
          git push
